#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Sandeep Sadanandan <grep@whybenormal.org>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export TERM=xterm-256color
PLATFORM='UNKNOWN'
UNAMESTR=`uname`
if [[ "$UNAMESTR" == 'Linux'  ]]; then
  PLATFORM='LINUX'
elif [[ "$UNAMESTR" == 'Darwin'  ]]; then
  PLATFORM='OSX'
fi

# Options
export EDITOR="vim"           # only fools wouldn't do this ;-)
DISABLE_CORRECTION="true"

setopt APPEND_HISTORY         # Don't overwrite, append!
setopt AUTO_NAME_DIRS         # This will use named dirs when possible
setopt AUTO_PUSHD             # This makes cd=pushd
setopt EXTENDED_GLOB          # I don't know why I never set this before.
setopt EXTENDED_HISTORY       # Save the time and how long a command ran
setopt GLOB_COMPLETE          # If we have a glob this will expand it
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS   # Even if there are commands inbetween commands that are the same, still only save the last one
setopt HIST_IGNORE_DUPS       # If I type cd and then cd again, only save the last one
setopt HIST_NO_STORE
setopt HIST_REDUCE_BLANKS     # Pretty    Obvious.  Right?
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY            # When using a hist thing, make a newline show the change before executing it.
setopt MULTIOS                # Now we can pipe to multiple outputs!
setopt NO_BEEP                # beeps are annoying
setopt NO_CASE_GLOB           # Case insensitive globbing
setopt CLOBBER                # Keep echo "station" > station from clobbering station
setopt NOCORRECTALL
#setopt NO_FLOW_CONTROL       # If I could disable Ctrl-s completely I would!
setopt NO_HUP
setopt NUMERIC_GLOB_SORT      # Be Reasonable!
setopt PUSHD_MINUS
setopt RC_EXPAND_PARAM        # hows about arrays be awesome?  (that is, frew${cool}frew has frew surrounding all the variables, not just first and last
setopt RMSTARSILENT
setopt SHARE_HISTORY          # Killer: share history between multiple shells
setopt ZLE                    # use magic (this is default, but it can't hurt!)
unsetopt AUTO_CD              # why would you type 'cd dir' if you could just type 'dir'?
unsetopt CORRECT_ALL
unsetopt CORRECT              # Spell check commands!  (Sometimes annoying)
unsetopt HIST_IGNORE_SPACE    # If a line starts with a space, don't save it.
unsetopt RM_STAR_WAIT         # 10 second wait if you do something that will delete everything.  I wish I'd had this before...

# KEY BINDINGS
#setopt VI
bindkey -M viins \\C-R history-incremental-search-backward
bindkey -M vicmd \\C-R history-incremental-search-backward
bindkey "" backward-delete-word
bindkey "OH" beginning-of-line
bindkey "OF" end-of-line
bindkey "[5~" history-beginning-search-backward
bindkey "[6~" history-beginning-search-forward
bindkey "" beginning-of-line
bindkey "" end-of-line
bindkey "[3~" delete-char
bindkey "" backward-kill-line

autoload run-help
HELPDIR=~/zsh_help
LS_OPTIONS='-G'

# Global alias(es)
alias -g J="| jq '.'"
alias -g P="| pbcopy"
alias -g G="| grep"
alias -g L="| less"
alias -g H="history 1"
alias -g Cf="| cut -f "
alias -g Cb="| cut -b "
alias -g CF="| cut -f 4 -d ' ' | tr -d '[]'"

# Other alias
alias ls='ls --color=tty'
alias fa='find . -iname "*"'
alias fd='find . -type d -iname "*"'
alias ff='find . -type f -iname "*"'
alias gdiff='git difftool --extcmd=diff'
alias glog='git log --pretty=format:"%h %s" --graph --oneline'
alias gst='git status'
alias gad='git add .'
alias youtubemp3='youtube-dl --prefer-ffmpeg --extract-audio --audio-format mp3 '
alias md='nocorrect mkdir -p'
alias rf='rm -rf'

# Jump commands
#alias kotai='cd $HOME/go/src/github.com/kotaicode'
#alias silly='cd $HOME/go/src/github.com/sillyfellow'
#alias keyline='cd $HOME/go/src/github.com/crispymtn/keyline-gattaca'
#alias maersk='cd $HOME/go/src/bitbucket.org/opremic.solutions:7999/maer/simulatorc'
#alias iata='cd $HOME/go/src/bitbucket.org/opremic.solutions:7999/iata/simulator'
#alias baub='cd $HOME/go/src/github.com/tlubinski/ibt-backend'
#alias bauw='cd $HOME/go/src/github.com/tlubinski/ibt-webapp'
#alias baup='cd $HOME/go/src/github.com/tlubinski/ibt-ipad'
#alias clinks='cd $HOME/go/src/bitbucket.org/creditlinks/app-creditlinks/'

# ZPrezto Jumps
alias j="jump"
alias b="bookmark"
alias d="deletemark"
alias s="showmarks"

# Fiz zsh extra checks. I know what I'm doing
unalias rm
unalias cp

# Run emacs daemon
pgrep emacs || emacs --daemon
alias emax="emacsclient -t"                      # used to be "emacs -nw"
alias semax="sudo emacsclient -t"                # used to be "sudo emacs -nw"
alias emaxsc="emacsclient -c -a emacs"           # new - opens the GUI with alternate non-daemon

alias -s go='vim -O'

# HISTORY BUSINESS
HISTFILE=~/.history   # Where it gets saved
SAVEHIST=10000        # Remember about a years worth of history (AWESOME)
HISTSIZE=10000

# Custom stuff
source ~/.aws_secrets.env
source ~/bin/ccd
#source ~/bin/energis.sh
#source ~/bin/metro.sh
#source ~/bin/kotai.sh
source ~/bin/utils

# Load keys
eval `ssh-agent -s`
ssh-add ~/.ssh/id_rsa
ssh-add ~/.ssh/energis_ops_key
ssh-add ~/.ssh/repricon_key
ssh-add ~/.ssh/airtango.private_key

# Linguistics and Paths

# R
alias R='R --no-save'
if [ -n $(which Rscript)  ]; then
  export PKG_CXXFLAGS=`Rscript -e "Rcpp:::CxxFlags()"`
  export PKG_LIBS=`Rscript -e "Rcpp:::LdFlags()"`
fi

# Android
if [ -d "/opt/android-studio/" ] ; then
  export PATH="$PATH:/opt/android-studio/bin"
fi

# Go
export PATH=/usr/local/go/bin:$PATH
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH

# JS (Node)
export NODEROOT=/usr/local/node
export PATH=$NODEROOT/bin:$PATH

# SQL
if [[ "$PLATFORM" == 'OSX'  ]]; then
  export PSQLINST=/Applications/Postgres.app/Contents/Versions/10/bin
  export PATH=$HOME/bin:$GOPATH/bin:$PATH:$PSQLINST
  export PATH="/usr/local/opt/imagemagick@6/bin:$PATH"

  # update paths for gnu coreutils
  export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
  export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

  # alias vim='mvim -v'
else
  setxkbmap -option compose:ralt|| echo "Couldn't set the compose key"
fi

# Python
export PYTHONSTARTUP=~/.pythonrc.py
source /usr/local/bin/virtualenvwrapper.sh

# Rvm, Ruby
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
if [ -d "$HOME/.rvm" ] ; then
fi

# Rust
if [ -d "$HOME/.cargo/bin" ] ; then
  export PATH="$HOME/.cargo/bin:$PATH"
fi

# Happy happy happy, and own stuff
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
  PATH="$HOME/bin:$PATH"
  sh ~/bin/sigmaker.sh
fi

# set PATH to user macvim
if [ -d "/Applications/MacVim.app/Contents/bin" ] ; then
  PATH="/Applications/MacVim.app/Contents/bin:$PATH"
fi

# set PATH to user maxTex
if [ -d "/Library/TeX/texbin" ] ; then
  export PATH="/Library/TeX/texbin":$PATH
fi

# Mark it loaded
export ZSHLOADED=YES

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin:."

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
